import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./_components/top-bar";
import { fontBody } from "./_utils/_fonts";
import Footer from "./_components/footer"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={fontBody.className}>
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
